version: '3'
services:
  application_db:
    build: ./db
    image: db
    ports:
      - "5432:5432"
  rest:
    build: ./rest
    image: rest
    ports:
      - "7070:7070"
    depends_on:
      - application_db
  ui:
    build: ./ui
    image: ui
    ports:
      - "9090:3000"
      - "35729:35729"
    volumes:
      - "./ui:/usr/src/app"
      - "/usr/src/app/node_modules"
    environment:
     - NODE_ENV=development
     - CHOKIDAR_USEPOLLING=true
  keycloak_db:
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
  keycloak:
    image: jboss/keycloak:4.0.0.Final
    ports:
      - "8080:8080"
    depends_on:
      - keycloak_db
    environment:
      - DB_VENDOR=MYSQL
      - MYSQL_ADDR=keycloak_db
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password