version: '3'
services:
  application_db:
    build: ./db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
  rest:
    build: ./rest
    image: rest
    ports:
      - "7070:7070"
  ui:
    build: ./ui
    image: ui
    ports:
      - "9090:3000"
      - "35729:35729"
    volumes:
      - "./ui:/usr/src/app"
      - "/usr/src/app/node_modules"
    environment:
     - NODE_ENV=development
     - CHOKIDAR_USEPOLLING=true
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
  keycloak:
    image: jboss/keycloak:4.0.0.Final
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_VENDOR=POSTGRES
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT_5432_TCP_ADDR=postgres